name: Build and Push Docker Image

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set lowercase repo owner
      id: vars
      run: echo "repo_owner_lower=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Build Docker image
      run: |
        IMAGE_NAME=ghcr.io/${{ env.repo_owner_lower }}/schema-migrator
        docker build -t $IMAGE_NAME:latest .

    - name: Push Docker image
      run: |
        IMAGE_NAME=ghcr.io/${{ env.repo_owner_lower }}/schema-migrator
        docker push $IMAGE_NAME:latest
