name: Build and Push Docker Image

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/gordon240722/schema-migrator
          docker build -t $IMAGE_NAME:latest .

      - name: Show repo owner
        run: |
          echo "repo owner: ${{ github.repository_owner }}"

      - name: Push Docker image
        run: |
          IMAGE_NAME=ghcr.io/gordon240722/schema-migrator
          docker push $IMAGE_NAME:latest
