name: Run FluentMigrator for all tenants

on:
  push:
    branches: [ master ]   # 你也可以改成其他 branch 名稱
  workflow_dispatch:     # 也支援手動執行

jobs:
  migrate:
    runs-on: windows-latest
    env:
      ConnectionStrings__DefaultConnection: ${{ secrets.DEFAULT_CONNECTION }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release

    - name: Publish project
      run: dotnet publish ./SchemaMigrationTool/SchemaMigrationTool.csproj --configuration Release --output ./published

    - name: Run FluentMigrator (multi-tenant)
      run: dotnet ./published/SchemaMigrationTool.dll
